### ISSUE TITLE
Switch meta puzzle from "delay reveal by a week" to "reveal answer instantly" once the puzzle has been published

### ISSUE THREAD

**Issue by malihanda** [mdirolf/crosshare#339] opened 2021-11-09 15:59 UTC
I don't see a way to change this.

**Comment by mdirolf** [comment] 2021-11-09 16:01
Yup it's not available on the edit page yet. In the meantime if you need to change one just LMK (here or via email/twitter) and I can manually update.

Closing as a duplicate of https://github.com/mdirolf/crosshare/issues/331

**Closed by mdirolf** 2021-11-09 16:01 UTC

**Comment by malihanda** [comment] 2021-11-09 16:09
Can you update this one pls to be instant reveal: https://www.7xwords.com/daily/11/11-09.html

**Comment by mdirolf** [comment] 2021-11-09 16:13
Shuold be updated once the cache clears in ~1hr or less
