### ISSUE TITLE
Puzzle preview clue listing

### ISSUE THREAD

**Issue by eoxford** [mdirolf/crosshare#365] opened 2021-12-29 15:46 UTC
On Discord (and presumably other sites where links can be embedded), if you post a link to a Crosshare puzzle, the preview will be the clues in the puzzle. But the clues are listed in alphabetical order instead of the order they actually appear in the puzzle.

**Comment by mdirolf** [comment] 2021-12-29 15:48
Thank you! Closing as duplicate of https://github.com/mdirolf/crosshare/issues/149 which should be fixed in the next deploy

**Closed by mdirolf** 2021-12-29 15:48 UTC
